### PR TITLE
added display properties to xs and sm size boxes to remove images

### PR DESCRIPTION
**Pull request by rgedwill**
Added display properties to Box elements of home page to hide them on small screens

### CODE REVIEW

**Review by dhuangg — CHANGES_REQUESTED** [review]
Functionality looks good - For any tag with over 2 attributes, use new lines. For example:
```
<Box 
    boxShadow={4}
    className="imageContainer"
    display={...}
/>
```

**Comment by rgedwill** [comment]
CTA

Where should the edit (pencil) button be? I figured it would be in one of these places, I'm thinking #1

**Comment by dhuangg** [comment]
Wait, this is a ticket for the main omou app, not the marketing portal.
You're making a PR to the marketing portal.

But also, this ticket isnt for this page. it should be when you're on the
account tab and you change the display to cards instead of a list.

**Comment by CalvinFronda** [comment]
Went ahead and pulled your branch but none of the home images are loading. Is this an issue only I'm seeing or is this for everyone else. 
Screen Shot 2020-05-12 at 6 22 57 PM

**Comment by rgedwill** [comment]
Yeah my bad I had both open in tabs and I posted that comment on the wrong one @dhuangg

**Comment by rgedwill** [comment]
@CalvinFronda I had that issue at one point when I was fixing it but I am not having it right now when I run my branch

**Pull request merged**
